<?php
namespace FASTPIXEL;

defined('ABSPATH') || exit;

if (!class_exists('FASTPIXEL\FASTPIXEL_Tab_Css')) {
    class FASTPIXEL_Tab_Css extends FASTPIXEL_UI_Tab
    {
        protected $slug = 'css';
        protected $order = 4.5;
        protected $custom_css_error = false;
        protected $custom_css_value = null;

        public function __construct() {
            parent::__construct();
            $this->name = esc_html__('CSS', 'fastpixel-website-accelerator');
            add_action('fastpixel/tabs/loaded', [$this, 'save_options'], 13);
        }

        public function settings() {
            register_setting(FASTPIXEL_TEXTDOMAIN, 'fastpixel_css_two_phase_loading', [
                'type'    => 'boolean',
                'default' => true
            ]);
            register_setting(FASTPIXEL_TEXTDOMAIN, 'fastpixel_custom_css', [
                'type'              => 'string',
                'sanitize_callback' => [$this, 'sanitize_fastpixel_custom_css']
            ]);
            add_settings_section(
                'fastpixel_settings_section-css',
                '',
                false,
                FASTPIXEL_TEXTDOMAIN . '-css'
            );
            $show_two_phase_loading = false; // Hidden for now.
            if ($show_two_phase_loading) {
                $field_title = esc_html__('Two-phase loading', 'fastpixel-website-accelerator');
                add_settings_field(
                    'fastpixel_css_two_phase_loading',
                    $field_title,
                    [$this, 'field_two_phase_loading_cb'],
                    FASTPIXEL_TEXTDOMAIN . '-css',
                    'fastpixel_settings_section-css',
                    [
                        'class' => 'fastpixel-settings-form-row',
                        'label' => $field_title
                    ]
                );
            }
            $field_title = esc_html__('Custom CSS', 'fastpixel-website-accelerator');
            add_settings_field(
                'fastpixel_custom_css',
                $field_title,
                [$this, 'field_custom_css_cb'],
                FASTPIXEL_TEXTDOMAIN . '-css',
                'fastpixel_settings_section-css',
                [
                    'class' => 'fastpixel-settings-form-row',
                    'label' => $field_title
                ]
            );
        }

        public function field_two_phase_loading_cb($args) {
            $enabled = $this->functions->get_option('fastpixel_css_two_phase_loading', true);
            $this->be_functions->print_checkbox([
                'field_name'  => 'fastpixel_css_two_phase_loading',
                'checked'     => $enabled,
                'label'       => $args['label'],
                'description' => esc_html__('Generate Critical CSS and load the CSS in two phases to reduce initial render time.', 'fastpixel-website-accelerator')
            ], true);
        }

        public function field_custom_css_cb($args) {
            $custom_css = stripslashes($this->functions->get_option('fastpixel_custom_css'));
            if ($this->custom_css_value !== null) {
                $custom_css = $this->custom_css_value;
            }
            $description = esc_html__('Use this option to add custom CSS to the critical CSS generated by FastPixel, for example if you need to 
                improve the early display of dynamically rendered items such as menus. The added custom CSS should not contain HTML tags and be properly formatted. 
                Make sure you know what you are doing.', 'fastpixel-website-accelerator');
            $error_message = '';
            if ($this->custom_css_error) {
                $error_message = sprintf(
                    esc_html__('Settings not saved, CSS is not valid. Please %s.', 'fastpixel-website-accelerator'),
                    $this->custom_css_error === 'html' 
                        ? esc_html__('remove HTML tags', 'fastpixel-website-accelerator')
                        : esc_html__('check curly braces', 'fastpixel-website-accelerator')
                    );
            }
            $this->be_functions->print_textarea([
                'field_name'  => 'fastpixel_custom_css',
                'field_value' => $custom_css,
                'label'       => $args['label'],
                'placeholder' => ".example .menu .item { background-image: \"/img/bgmenu.jpg\" }\n.other-class { color: red }",
                'description' => $description,
                'error'       => $error_message
            ], true);
        }

        public function sanitize_fastpixel_custom_css($value) {
            $error = $this->validate_fastpixel_custom_css($value);
            if ($error !== '') {
                return $this->functions->get_option('fastpixel_custom_css');
            }
            $sanitized = sanitize_textarea_field($value);
            return $sanitized;
        }

        protected function validate_fastpixel_custom_css($value) {
            if (preg_match('/<[^>]+>/', $value)) {
                return 'html';
            }
            if (!$this->has_balanced_braces($value)) {
                return 'braces';
            }
            return '';
        }

        protected function has_balanced_braces($value) {
            $depth = 0;
            $length = strlen($value);
            for ($i = 0; $i < $length; $i++) {
                $char = $value[$i];
                if ($char === '{') {
                    $depth++;
                } elseif ($char === '}') {
                    $depth--;
                    if ($depth < 0) {
                        return false;
                    }
                }
            }
            return $depth === 0;
        }

        public function save_options() {
            if (sanitize_text_field($_SERVER['REQUEST_METHOD']) !== 'POST' || (defined('DOING_AJAX') && DOING_AJAX) ||
                check_admin_referer('fastpixel-settings', 'fastpixel-nonce') == false ||
                empty($_POST['fastpixel-action']) || sanitize_key($_POST['fastpixel-action']) != 'save_settings') {
                return;
            }
            $two_phase = isset($_POST['fastpixel_css_two_phase_loading']) && 1 == sanitize_text_field($_POST['fastpixel_css_two_phase_loading']) ? 1 : 0;
            $this->functions->update_option('fastpixel_css_two_phase_loading', $two_phase);

            if (isset($_POST['fastpixel_custom_css'])) {
                $raw_css = wp_unslash($_POST['fastpixel_custom_css']);
                $error = $this->validate_fastpixel_custom_css($raw_css);
                if ($error !== '') {
                    $this->custom_css_error = $error;
                    $this->custom_css_value = $raw_css;
                    return;
                }
                $custom_css = sanitize_textarea_field($raw_css);
                $this->functions->update_option('fastpixel_custom_css', $custom_css);
            }
        }
    }
    new FASTPIXEL_Tab_Css();
}
